### ISSUE TITLE
What is the meaning of returning value in failed blackjack algorithm?

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/coinselect#14]
What does this represent

`return { fee: feeRate * bytesAccum }`

at failed blackjack algorithm? It doesn't seem like any actual transaction :) and the fee doesn't correspond to much either

**Comment by dcousens** [comment]
@runn1ng when possible,  a `fee` is returned to indicate to a higher-level UI or algorithm what the prospective fees would *at least* be given the current set of inputs and outputs.

This can provide support for users to iteratively build transactions, seeing what the fees might be, even if a valid, balanced transaction doesn't exist [yet].

**Comment by dcousens** [comment]
For example,  I want to send a transaction with 200 satoshi/byte fee,  but I can't afford it.
Without `fee` being returned,  I wouldn't be able to inform the user "transaction fee would be X,  you only have Y",  I could only say "not enough funds".

**Comment by runn1ng** [comment]
OK, that makes some sense, altough I am still not sure if it doesn't end up more confusing than informative.
