### ISSUE TITLE
Layer for confirmations

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/coinselect#23]
I am thinking about adding another "layer" for coin selection, but I am not sure if to take it here or to a separate library.

Some inputs are confirmed and some are unconfirmed; some are from user himself and some are from other people. In coin selection, you first want to try only the confirmed inputs with 6+ confs, except for your own inputs that you can spend with 1+ conf, and only then use unconfirmed; except for coinbase inputs, that need to be confirmed with 50+ confs (I think).

However, right now, inputs in coinselect don't have information about that, and doesn't take that into account.

Do you think it should be here, or in another library?

**Comment by dcousens** [comment]
Discussion here or in #25?

I think these metrics can be accounted for using a specialized `utxo` ordering.

**Comment by runn1ng** [comment]
OK let's keep it at #25, will close this issue
