### ISSUE TITLE
How do you create a 'wallet' that has getChangeAddress()?

### ISSUE THREAD

**Issue by j3ko** [bitcoinjs/coinselect#27]
On the readme there is:

```javascript
outputs.forEach(output => {
  // watch out, outputs may have been added that you need to provide
  // an output address/script for
  if (!output.address) {
    output.address = wallet.getChangeAddress()
  }

  txb.addOutput(output.address, output.value)
})
```

where does wallet come from?

**Comment by rbndg** [comment]
I believe it's implying that you should set the output.address to the wallet address you want to get the change for.

**Comment by dcousens** [comment]
I'll update this example to be more complete in future;  and will use the [new `bip32` module](https://github.com/bitcoinjs/bip32).

Traditionally, `getChangeAddress` will simply be a wrapper around `bip32.fromSeed(seed).derivePath('m/0'/1'/i)`,  where `i` is the offset into that account,  and `i` should increment by `1` for each `output.address`.

**Comment by j3ko** [comment]
Thanks for the quick reply @dcousens, If I can ask for a bit more help.  I've been trying to implement this, it looks like ```bip32.fromSeed()``` is so new, it hasn't made it into any bip32 releases?

I tried adding the package directly from master but it looks like master is also missing a file: ```let ecc = require('./ecc')```.

It might be too bleeding edge for my purposes, how was this accomplished before the new bip32 module?

**Comment by dcousens** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/hdnode.js#L31

``` js
bitcoinjs.HDNode.fromSeedBuffer(seed).derivePath(`m/0'/1'/${k}`).getAddress()
```

**Comment by rbndg** [comment]
@dcousens is it incorrect to set any bitcoin address as the changeAddress or do we have to use deterministic wallet?

**Comment by dcousens** [comment]
@rbndg you can do whatever you like.
I can only recommend that you keep backups of any private keys you generate :stuck_out_tongue_closed_eyes:

**Comment by rbndg** [comment]
Yeah, dealing with deterministic wallets seeds is much better 😊

**Comment by j3ko** [comment]
thanks @rbndg works like a charm! :grin:
