### ISSUE TITLE
Unsure how to use?

### ISSUE THREAD

**Issue by SethMcGuire** [bitcoinjs/coinselect#28]
I can't seem to get this to work how I want it to. I want it to select inputs automatically. Can someone please help me. This is my code : `    createTransaction = (e) => {
        e.preventDefault()
        const {address, privateKey, add, amount} = this.state;
        var hashURL = `https://api.blockcypher.com/v1/btc/test3/addrs/${address}`

            axios.get(hashURL).then((response) => {
                this.setState({
                    hash1: response.data.txrefs[0].tx_hash,
                    hash1Val: response.data.txrefs[0].value
                })
            }).then((result) => {

            var tx = new bitcoin.TransactionBuilder(testnet);
    
            var txId = this.state.hash;
            var txIdVal = this.state.hashVal;

            console.log(txId);

            tx.addInput(txId, 1)
    
            tx.addOutput(this.state.add, amount)
            //send change back and make fee = .001BTC
            tx.addOutput(this.state.address, hash1val - amount - 100000)
    
            var keyPair2 = bitcoin.ECPair.fromWIF(privateKey, testnet);
    
            tx.sign(0, keyPair2);
            console.log(tx.build().toHex());
            }
        )
Can someone please show me how to select inputs automatically? Thank you!`

**Comment by dcousens** [comment]
You need multiple inputs to select from first.  You only have `txId` and `txIdVal`?

Then you need to provide `coinselect`:
``` js
let feeRate = 100 // aka 100 satoshis per byte
let { inputs, outputs, fee } = coinselect([
  {
     txId: txId,
     vout: 1,
     value: txIdVal
  }
], [{
  address: this.state.address,
  value: this.state.add
}], feeRate)

if (!inputs) throw new Error('No valid Transaction exists')

outputs.forEach((x) => {
  if (x.address) return
  x.address = this.state.address // the change address
})

let txb = new bitcoin.TransactionBuilder(testnet)
inputs.forEach(x => txb.addInput(x.txId, x.vout))
outputs.forEach(x => txb.addOutput(x.address, x.value))
inputs.forEach((x, i) => txb.sign(i, keyPair))

txb.build().toHex()
```

**Comment by SethMcGuire** [comment]
Thanks for the help! I don't mean to be a bother, but do you know how I can make my app get all the txIds automatically? I'm pretty stuck here.

**Comment by dcousens** [comment]
> but do you know how I can make my app get all the txIds automatically?

The question here,  is `txIds`... for __what__?

If you have a list of addresses,  you can use a block explorer,  of which there are many.

https://blockchain.info/q
https://www.blocktrail.com/api
https://btc.com/api-doc
https://www.blockcypher.com/quickstart/
https://www.smartbit.com.au/api

They come and go.
