### ISSUE TITLE
inputs undefined  &  outputs undefined  ,why?

### ISSUE THREAD

**Issue by Yangk030208** [bitcoinjs/coinselect#30]
I wrote this code as a demo, but I got undefined, what's wrong?
`
let { inputs, outputs, fee } = coinSelect(utxos, targets, feeRate);
`

**Comment by Yangk030208** [comment]
There are other errors in my code, sorry.

**Comment by dcousens** [comment]
@Yangk030208 no problem!
Please post your issue/problem if it might help others :+1:
