### ISSUE TITLE
Doubt about feeRate unit

### ISSUE THREAD

**Issue by penghap** [bitcoinjs/coinselect#42]
1. Is the feeRate must be positive integer ? 
```js
function uintOrNaN (v) {
  if (typeof v !== 'number') return NaN
  if (!isFinite(v)) return NaN
  if (Math.floor(v) !== v) return NaN
  if (v < 0) return NaN
  return v
}

``` 
[uintOrNaN](https://github.com/bitcoinjs/coinselect/blob/288f24d221e5f1e5beac883043cc706914b2b2bd/utils.js#L30)

2. The rpc of [estimatesmartfee](https://bitcoincore.org/en/doc/0.16.0/rpc/util/estimatesmartfee/) result,  fee rate in BTC/kB, So the feeRate unit would be better `satoshis per kB` than `satoshis per byte` ?

**Comment by junderw** [comment]
1. yes
2. RPC is BTC / kB, this library uses satoshi / byte.

**Comment by penghap** [comment]
The current estimatesmartfee is
```
{"result":{"feerate":0.00209660,"blocks":2},"error":null,"id":1}
```
the feeRate maybe is 209660 satoshis per kB，209660/1024 satoshis per byte, The error will be magnified, in the utxos the value has multiplied by 10e8, so use satoshis per kB would be better ?

**Comment by junderw** [comment]
1 kB = 1000 bytes
1 kiB = 1024 bytes

just fyi.

Bitcoin estimates use kB not kiB

**Comment by penghap** [comment]
Thanks for reply.
