### ISSUE TITLE
[QUESTION] Source of UTXOs?

### ISSUE THREAD

**Issue by ekkis** [bitcoinjs/coinselect#44]
this is very cool but how do I get a list of UTXOs given a private key?

**Comment by ekkis** [comment]
I see that blockchain.com has an api allowing me to retrieve the utxos, but the format it comes back in doesn't seem correct given what this module is expecting.  for example, I get:

> {
>     "unspent_outputs":[
>         {
>             "tx_age":"1322659106",
>             "tx_hash":"e6452a2cb71aa864aaa959e647e7a4726a22e640560f199f79b56b5502114c37",
>             "tx_index":"12790219",
>             "tx_output_n":"0",
>             "script":"76a914641ad5051edd97029a003fe9efb29359fcee409d88ac", (Hex encoded)
>             "value":"5000661330"
>         }
>     ]
> }

so there's not `txId` or `vout` like the sample code is expecting.  and the hash, per the documentation is backwards... is this usable at all?

**Comment by junderw** [comment]
tx_hash == txId (good to use as is. In your example, e6452a2cb71aa864aaa959e647e7a4726a22e640560f199f79b56b5502114c37 is the correct string to pass the library, no need to revers the byte order)
tx_output_n == vout (Convert to number with parseInt)
value == value (But you should convert to Number first with parseInt. 21million Bitcoin fits within JavaScript's 53 bit Number integers, so it should be fine.)

**Comment by ekkis** [comment]
a million thanks for this
