### ISSUE TITLE
TransactionBuilder is now deprecated

### ISSUE THREAD

**Issue by ekkis** [bitcoinjs/coinselect#45]
the main page shows an example using the TransactionBuilder.  apparently we now need to use the `Psbt` class instead.  could we modify the read me to use this new method?

**Comment by junderw** [comment]
Nice catch! Will work on it.

**Comment by ekkis** [comment]
thanks for the changes.  could you demonstrate how to sign one of these transactions? the object returned by the new `.Psbt()` no longer has a `.sign()` and I don't find any examples.  I'm tempted to go back to the TransactionBuilder...

**Comment by ekkis** [comment]
btw, it will sort of look like this:
```js
tx.signInput(0, signingKey);
tx.validateSignaturesOfInput(0);
tx.finalizeAllInputs();
console.log(tx.extractTransaction().toHex());
```

**Comment by junderw** [comment]
There are tons of examples in bitcoinjs-lib integration tests (linked on the README) and PSBT is not a part of the coinselect library, so explaining it's use here is irrelevant.

**Comment by ekkis** [comment]
you're right.  thanks
