### ISSUE TITLE
No inputs or outputs generated

### ISSUE THREAD

**Issue by ekkis** [bitcoinjs/coinselect#47]
I'd add a label "Question / Help Wanted" to this issue but I can't figure out how to do it.  I'm working on the TESTNET and with the following query:
```
curl https://api.blockcypher.com/v1/btc/test3/addrs/mjGtZWXgPdbLUZYWtDqVTfbFieVzXFfSEj?unspendOnly=true
```
I get the following Json:
```json
{
  "address": "mjGtZWXgPdbLUZYWtDqVTfbFieVzXFfSEj",
  "total_received": 10631,
  "total_sent": 0,
  "balance": 10631,
  "unconfirmed_balance": 0,
  "final_balance": 10631,
  "n_tx": 2,
  "unconfirmed_n_tx": 0,
  "final_n_tx": 2,
  "txrefs": [
    {
      "tx_hash": "6861bc1cb3564c907343a6dc83651827f9da1346e36417ce6b46a5753d32a033",
      "block_height": 1657954,
      "tx_input_n": -1,
      "tx_output_n": 0,
      "value": 8336,
      "ref_balance": 10631,
      "spent": false,
      "confirmations": 10,
      "confirmed": "2020-01-10T04:27:39Z",
      "double_spend": false
    },
    {
      "tx_hash": "e6a1fb15c1480050179b8dc6325dfacfb35c869b2f8f0397e64625b0e48b9b2c",
      "block_height": 1657484,
      "tx_input_n": -1,
      "tx_output_n": 0,
      "value": 2295,
      "ref_balance": 2295,
      "spent": false,
      "confirmations": 480,
      "confirmed": "2020-01-09T22:16:00Z",
      "double_spend": false
    }
  ],
  "tx_url": "https://api.blockcypher.com/v1/btc/test3/txs/"
}
```
which I digest like this:
```js
const CoinSelect = require('coinselect');
var utxos = o.txrefs.map(o => ({
    txId: o.tx_hash, vout: parseInt(o.tx_output_n), value: parseInt(o.value)
}));
var targets = [{address: dst, value}];
var ret = CoinSelect(utxos, targets, feeRate);
```
such that what I feed the function looks like this (utxos):
```js
[ { txId:
     '6861bc1cb3564c907343a6dc83651827f9da1346e36417ce6b46a5753d32a033',
    vout: 0,
    value: 8336 },
  { txId:
     'e6a1fb15c1480050179b8dc6325dfacfb35c869b2f8f0397e64625b0e48b9b2c',
    vout: 0,
    value: 2295 } ]
```
and targets:
```js
[ { address: '2N7nSZjfqikj4oVkCqaLB3CNMY3TA72PbNY', value: 500 } ]
```
however, what the function returns to me is:
```js
{ fee: 18590 }
```
which means something is failing.  I can't figure it out.  is it obvious to anyone what it might be?

**Comment by junderw** [comment]
You're shadowing use of variable `o`

**Comment by ekkis** [comment]
yeah.  that's ok.  the innermost value is used.  I just noticed that the balance on the account is 10631 and the fee is 18590!  I'm only trying to send 500 but with the fee I think it's failing because there isn't enough balance.  it's a rather large fee... I think I need to increase the balance for this to work

**Comment by ekkis** [comment]
that was it.  I didn't have enough balance.  sorry to bother anyone

**Comment by junderw** [comment]
did you use feeRate = 100?

That's waaaaaaay too high.

feeRate 1 is fine

**Comment by ekkis** [comment]
ah.  I used `feeRate = 55` as indicated on the README to this project.  also, I'm having a problem when I try to push the transaction: https://bitcoin.stackexchange.com/questions/92743/transaction-fails-to-validate-error-running-script and I think it might be the issue of the `tx_input_n` vs `tx_output_n`.  as you can see I'm feeding your module the latter but I have a feeling I might need the former.  can you confirm?

**Comment by junderw** [comment]
nope. if it's a script error in the transaction validation it has nothing to do with that.

If you got any of those wrong the error would say "invalid pointer" or something.

If the error says "script verification failed" etc. that means all the pointers are correct, you're pointing to the right coins but you somehow signed it wrong etc.
