### ISSUE TITLE
Consider Output Address Types

### ISSUE THREAD

**Issue by itsMikeLowrey** [bitcoinjs/coinselect#51]
How does coinselect(utxos, targets, feeRate) get a correct transaction size when coinselect does not know what type of change address will be used? The change address could be a really large script that could push the fee rate below the required fee rate or make change not worth keeping. Great library and thanks so much for helping me clarify my understandings.

**Comment by junderw** [comment]
1. Currently such a script is non-standard, so it won't propagate across the network.
2. That said, currently it assumes the change will be 25 byte script (P2PKH). The only other standard output script that is larger is P2WSH which is 35 byte script. (not P2SH embedded P2WSH, which is 23)

So yes, your estimate would be 10 bytes off if your change output was a P2WSH script. Worst case scenario is around 5% (if your tx is as small as possible)

I'm open to suggestions on how to handle this.

**Comment by itsMikeLowrey** [comment]
Thanks for the info. I am building a multisig wallet that uses P2WSH and I see two possible solutions: 
1. We could change the default change script to P2WSH and have some fees be larger than expected but never smaller.
2. Leave the default change address type to P2PKH and take in an optional parameter that allows you to specify the change address type. 
I have looked over the code and I could make a pr doing either of these solutions. Thanks again for all the help.

**Comment by junderw** [comment]
I would say both.

1. We should make the most expensive default
2. We should allow people to set it to their wallet type to save some fees

I would also perhaps add a flag for low R, default false, that if true will shave one byte off each signature estimate (the R value being low)

Bitcoin Core now uses low R and BitcoinJS ECPair and bip32 objects support low R (default is off though).

**Comment by itsMikeLowrey** [comment]
I think the first pr might be to add a changeBytes() with a similar footprint to [outputBytes()](https://github.com/bitcoinjs/coinselect/blob/18b8a802fc40dad792115f79de36a6d77086e4c5/utils.js#L12).  I would also add a changeThreshold() similar to [dustThreshold()](https://github.com/bitcoinjs/coinselect/blob/18b8a802fc40dad792115f79de36a6d77086e4c5/utils.js#L16) and use it in finalize instead of dustThreshold().  In order for changeBytes() to have the output.script parameter, I was considering adding a changeScript parameter to coinselect(). I would then do a second pr addressing the default values for changescript etc. Thanks for the feedback.

**Comment by itsMikeLowrey** [comment]
This [PR](https://github.com/bitcoinjs/coinselect/pull/22) seems to address the bulk of these issues. I will try and get a grasp on that pr and help out.
