### ISSUE TITLE
No solution found if many inputs

### ISSUE THREAD

**Issue by sf-vio** [bitcoinjs/coinselect#59]
If there are many UTXOs being parsed into coinselect for a solution it does not appear to handle them and outputs no solution

**Comment by junderw** [comment]
Can you provide some dummy data that triggers the bug?

**Comment by sf-vio** [comment]
Just taking a couple of addresses from the explorer
	"sourceAddress":"12dRugNcdxK39288NjcDV4GX7rMsKCGn6B",
    "targetAddress":"1QC1k7hGP5oNy8tdvJYH9PAEx8UjniLZvV",
    "amount":1,
Amount is 1 BTC, you'll see in the file i'm converting to satoshis before coinselect
Please see file for UTXOs that were detected and then attempted to parse through coinselect
[coinselect issue 59.txt](https://github.com/bitcoinjs/coinselect/files/4791834/coinselect.issue.59.txt)

**Comment by junderw** [comment]
Remove the single quotes around the values. They should be numbers, not strings.
