### ISSUE TITLE
Order utxos by age

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/coinselect#6]
Coinselection should prefer older utxos and use unconfirmed utxos the latest

**Comment by dcousens** [comment]
@runn1ng this could easily be added to the [default sorting function](https://github.com/bitcoinjs/coinselect/blob/master/index.js#L7).

But any advanced heuristics may need to balance privacy and eventual fees in this equation.

**Comment by runn1ng** [comment]
Hm, I wrote this issue because that's how trezor web wallet currently selects coin, but thinking about it more, I am not sure what is the correct ordering.

There is a paper from late 2016 "Simulation-based Evaluation of Coin Selection Strategies", it seems the best utxo selection algorithm for low fees is from AndroidWallet, which sorts utxos by priority - that is, `value * inputAge`

This selection algorithm however results in the biggest utxo set.

The FIFO algorithm (that is, the same one that trezor wallet has right now) has only slightly higher fees and lower utxo set; however, it reveals the oldest user's utxo in every transaction (privacy concern).

I cannot decide at this moment :D (I just know I don't want to solve a knapsack problem here like Core does.)

We can provide all the strategies and leave it to the user to select, but I don't like that, I think the default should be sane.

**Comment by dcousens** [comment]
I don't think age is as important with priority dropped in most clients.
Close?

**Comment by runn1ng** [comment]
yep
