### ISSUE TITLE
Rationale for the blackjack strategy

### ISSUE THREAD

**Issue by runn1ng** [bitcoinjs/coinselect#9]
What is the rationale for using blackjack strategy, for selecting the exact match? 

It might create a lower fee, but will it create longer fees long-term?

**Comment by runn1ng** [comment]
It seems the code for the [simulation PDF](https://scalingbitcoin.org/papers/simulation-based-evaluation-of-coin-selection-strategies.pdf) is here  - https://github.com/Xekyo/CoinSelectionSimulator - I will look it up and try to run some experiments, to have something to reason with here :)

**Comment by dcousens** [comment]
@runn1ng there is an in-repo fee simulator: https://github.com/bitcoinjs/coinselect/tree/master/stats

I optimized the default export to be the lowest fees over time.

**Comment by dcousens** [comment]
> What is the rationale for using blackjack strategy, for selecting the exact match?

My approach assumes a descending by-value UTXO set,   with an accumulative exact match strategy.   It isn't perfect.

**Comment by runn1ng** [comment]
Thanks for comments!

I have tried to run the scala simulation code from @xekyo with the gambling hot wallet data (the simulation has a starting UTXO set and a set of value changes) - it actually seems that the strategies all return more or less the same fees, if you add total fees + cost to spend the remaining UTXOs.

The strategy that seem to work the best for the simulation (when total fees+cost to spend the rest is optimized) is [Branch and Bound](https://en.wikipedia.org/wiki/Branch_and_bound).

I will try to now run your simulation, plus try to understand @xekyo's Branch and Bound algorithm and port it into JS and into this code.

**Comment by runn1ng** [comment]
I am closing this, since BnB is a different strategy
